(() => {
  'use strict';

  const KEYS = { cart: 'fitmeal_cart', plan: 'fitmeal_plan', checkout: 'fitmeal_checkout' };
  const NAV = [
    ['index.html','Trang chủ','home'],
    ['Lotrinhhoa.html','Cá nhân hóa','plan'],
    ['menu.html','Thực đơn','menu'],
    ['orders.html','Đơn hàng','orders'],
    ['gioi-thieu.html','Về FitMeal','about'],
    ['tin-tuc.html','Cẩm nang','stories'],
    ['contact.html','Liên hệ','contact']
  ];

  const FALLBACK_PRODUCTS = [
    {"id":1,"title":"Combo Ức Gà Healthy","region":"Việt Nam","country":"Việt Nam","cal":520,"goal":"Giảm mỡ","price":79000,"oldPrice":null,"rating":null,"tags":["Healthy","Giàu đạm"],"image":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500","desc":"Ức gà áp chảo sốt tiêu xanh, ăn kèm gạo lứt Điện Biên và rau củ luộc."},
    {"id":2,"title":"Bún Lứt Trộn Bò Nam Bộ","region":"Việt Nam","country":"Việt Nam","cal":480,"goal":"Giữ dáng","price":74000,"oldPrice":null,"rating":null,"tags":["Bún lứt","Thịt bò"],"image":"https://images.unsplash.com/photo-1559847844-5315695dadae?w=500","desc":"Thịt bò mềm xào tỏi ít dầu, ăn kèm bún gạo lứt tươi và nước mắm chua ngọt ăn kiêng."},
    {"id":3,"title":"Cơm Gạo Lứt Chả Cá Thát Lát","region":"Việt Nam","country":"Việt Nam","cal":500,"goal":"Tăng cơ","price":84000,"oldPrice":null,"rating":null,"tags":["Cá tươi","Omega 3"],"image":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500","desc":"Chả cá thát lát hấp sả ăn kèm cơm gạo lứt và súp lơ xanh."},
    {"id":4,"title":"Phở Bò Gạo Lứt Chuẩn Vị","region":"Việt Nam","country":"Việt Nam","cal":450,"goal":"Ít Calo","price":74000,"oldPrice":null,"rating":null,"tags":["Bánh phở lứt","Nước dùng trong"],"image":"https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500","desc":"Phở bò tái nạm sử dụng bánh phở lứt ninh từ xương bò tách mỡ."},
    {"id":5,"title":"Gỏi Gà Xé Phay Hạt Quinoa","region":"Việt Nam","country":"Việt Nam","cal":410,"goal":"Giảm mỡ","price":74000,"oldPrice":null,"rating":null,"tags":["Gà thả vườn","Quinoa"],"image":"https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500","desc":"Ức gà xé phay trộn bắp cải tím, ngó sen và hạt diêm mạch."},
    {"id":6,"title":"Cơm Bò Lúc Lắc Gạo Lứt","region":"Việt Nam","country":"Việt Nam","cal":540,"goal":"Tăng cơ","price":85000,"oldPrice":null,"rating":null,"tags":["Bò Úc","Ớt chuông"],"image":"https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500","desc":"Thịt bò cắt khối vuông xào vừa chín tới giữ nguyên vị ngọt mọng nước."},
    {"id":11,"title":"Cơm Trộn Bibimbap Gạo Lứt","region":"Châu Á","country":"Hàn Quốc","cal":550,"goal":"Cân bằng","price":85000,"oldPrice":null,"rating":null,"tags":["Kim chi","Rau củ"],"image":"https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=500","desc":"Cơm gạo lứt ăn kèm thịt bò xào, trứng ốp la và 6 loại rau củ Hàn Quốc."},
    {"id":13,"title":"Cá Hồi Nướng Teriyaki Gạo Lứt","region":"Châu Á","country":"Nhật Bản","cal":580,"goal":"Tăng cơ","price":99000,"oldPrice":null,"rating":null,"tags":["Omega 3","Cá hồi"],"image":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500","desc":"Phi lê cá hồi áp chảo sốt Teriyaki ăn kiêng, đi kèm rong biển và cơm lứt."},
    {"id":14,"title":"Bento Gà Nướng Yakitori Healthy","region":"Châu Á","country":"Nhật Bản","cal":500,"goal":"Cân bằng","price":79000,"oldPrice":null,"rating":null,"tags":["Bento Nhật","Gà nướng"],"image":"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500","desc":"Hộp bento Nhật gồm gà nướng sả xiên, trứng cuộn Tamagoyaki và bắp cải."},
    {"id":16,"title":"Pad Thai Tôm Cơm Lứt","region":"Châu Á","country":"Thái Lan","cal":510,"goal":"Đổi vị","price":84000,"oldPrice":null,"rating":null,"tags":["Chua cay","Tôm sú"],"image":"https://images.unsplash.com/photo-1559847844-5315695dadae?w=500","desc":"Hủ tiếu lứt xào kiểu Thái với tôm sú, giá đỗ và đậu hũ rán kiềm mỡ."},
    {"id":17,"title":"Cà Ruy Xanh Gà Nướng Chuẩn Thái","region":"Châu Á","country":"Thái Lan","cal":540,"goal":"Thơm béo","price":85000,"oldPrice":null,"rating":null,"tags":["Sữa hạnh nhân","Cà ri"],"image":"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500","desc":"Ức gà nấu cà ri xanh sử dụng sữa hạnh nhân thay nước cốt dừa đậm đà."},
    {"id":18,"title":"Cà Ri Bò Ấn Độ Tikka Masala Light","region":"Châu Á","country":"Ấn Độ","cal":560,"goal":"Giàu gia vị","price":94000,"oldPrice":null,"rating":null,"tags":["Tikka Masala","Bò Úc"],"image":"https://images.unsplash.com/photo-1545247181-516773cae754?w=500","desc":"Bò Úc hầm sốt Masala kiểu Ấn dùng sữa chua Hy Lạp không béo."},
    {"id":26,"title":"Mì Ý Carbonara Sốt Kem Yến Mạch","region":"Châu Âu","country":"Ý","cal":520,"goal":"Dinh dưỡng","price":79000,"oldPrice":null,"rating":null,"tags":["Pasta nguyên cám","Kem yến mạch"],"image":"https://images.unsplash.com/photo-1621996346565-e3def616403c?w=500","desc":"Mì Spaghetti nguyên cám hòa quyện cùng sốt kem yến mạch và dăm bông nạc."},
    {"id":27,"title":"Mì Ý Sốt Bò Băm Bolognese Healthy","region":"Châu Âu","country":"Ý","cal":490,"goal":"Tăng cơ","price":79000,"oldPrice":null,"rating":null,"tags":["Bò băm","Cà chua tươi"],"image":"https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500","desc":"Pasta làm từ lúa mì lứt sốt bò Úc băm tươi và sốt cà chua tự nấu không đường."},
    {"id":28,"title":"Salad Cá Ngừ Ngô Ngọt Sốt Yogurt","region":"Châu Âu","country":"Anh","cal":380,"goal":"Giảm cân","price":74000,"oldPrice":null,"rating":null,"tags":["Cá ngừ","Sốt Yogurt"],"image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500","desc":"Cá ngừ ngâm nước, xà lách Romaine, ngô ngọt và sốt Hy Lạp Yogurt."},
    {"id":30,"title":"Salad Caesar Ức Gà Nướng lá Thơm","region":"Châu Âu","country":"Ý","cal":420,"goal":"Low Carb","price":74000,"oldPrice":null,"rating":null,"tags":["Salad Caesar","Gà nướng"],"image":"https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500","desc":"Rau xà lách Mỹ tươi giòn, ức gà nướng áp chảo và sốt Caesar ít béo."},
    {"id":32,"title":"Ức Vịt Nướng Sốt Cam Hy Lạp Cơm Lứt","region":"Châu Âu","country":"Pháp","cal":540,"goal":"Tăng cơ","price":88000,"oldPrice":null,"rating":null,"tags":["Ức vịt","Sốt cam Pháp"],"image":"https://images.unsplash.com/photo-1514944288352-fffac99f0bdf?w=500","desc":"Ức vịt áp chảo bỏ da sốt cam tươi thanh mát ngọt dịu chuẩn ẩm thực Pháp."},
    {"id":34,"title":"Cơm Paella Hải Sản Tây Ban Nha Healthy","region":"Châu Âu","country":"Tây Ban Nha","cal":530,"goal":"Giàu Omega","price":90000,"oldPrice":null,"rating":null,"tags":["Cơm Paella","Tôm mực"],"image":"https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500","desc":"Cơm nghệ gạo lứt xào tôm sú, mực tươi và nghêu nghệ kiểu Tây Ban Nha."},
    {"id":39,"title":"Steak Bò Áp Chảo Kèm Măng Tây","region":"Châu Mỹ","country":"Mỹ","cal":610,"goal":"Tăng cơ","price":108000,"oldPrice":null,"rating":null,"tags":["Bò Úc","Bít tết"],"image":"https://images.unsplash.com/photo-1544025162-d76694265947?w=500","desc":"Bít tết bò nạc áp chảo thảo mộc rosemary, măng tây và khoai tây nướng nguyên vỏ."},
    {"id":40,"title":"Burger Gà Lúa Mạch Kèm Salad","region":"Châu Mỹ","country":"Mỹ","cal":490,"goal":"Cheat Clean","price":79000,"oldPrice":null,"rating":null,"tags":["Burger nguyên cám","Ức gà"],"image":"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500","desc":"Vỏ bánh burger nguyên cám, nhân ức gà xay nướng lá oregano và cà chua."},
    {"id":41,"title":"Tôm Sốt Bơ Tỏi Kèm Bánh Mỳ Lúa Mạch","region":"Châu Mỹ","country":"Mỹ","cal":510,"goal":"Tăng cơ","price":84000,"oldPrice":null,"rating":null,"tags":["Tôm sú","Bơ ghee"],"image":"https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500","desc":"Tôm sú sốt bơ ghee thảo mộc ăn kèm bánh mì đen lúa mạch nướng giòn."},
    {"id":43,"title":"Taco Bò Băm Vỏ Bánh Ngô Mexico","region":"Châu Mỹ","country":"Mexico","cal":470,"goal":"Ít béo","price":74000,"oldPrice":null,"rating":null,"tags":["Taco","Vỏ ngô"],"image":"https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500","desc":"Bánh Taco vỏ ngô nguyên giòn nhồi bò nạc xào ớt chuông Salsa Mexico."},
    {"id":44,"title":"Burrito Ức Gà Đậu Đen Giảm Cân","region":"Châu Mỹ","country":"Mexico","cal":500,"goal":"Giàu chất xơ","price":79000,"oldPrice":null,"rating":null,"tags":["Burrito","Đậu đen"],"image":"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=500","desc":"Bánh cuộn Burrito nguyên cám nhồi ức gà nướng, đậu đen Mexico và sốt bơ avocado."},
    {"id":46,"title":"Churrasco Bò Úc Nướng Than Argentina","region":"Châu Mỹ","country":"Argentina","cal":580,"goal":"Tăng cơ mạnh","price":97000,"oldPrice":null,"rating":null,"tags":["Sốt Chimichurri","Bò nướng"],"image":"https://images.unsplash.com/photo-1544025162-d76694265947?w=500","desc":"Bò Úc nướng than sốt Chimichurri thảo mộc ngò tây chanh tỏi thơm ngon."},
    {"id":47,"title":"Lườn Cừu Nướng Lá Hương Thảo Úc","region":"Châu Đại Dương","country":"Úc","cal":590,"goal":"Giàu Sắt","price":97000,"oldPrice":null,"rating":null,"tags":["Thịt cừu Úc","Rosemary"],"image":"https://images.unsplash.com/photo-1544025162-d76694265947?w=500","desc":"Sườn cừu Úc nướng lá hương thảo ăn kèm khoai tây nghiền sữa hạnh nhân."},
    {"id":48,"title":"Barramundi Cá Chẽm Nướng Bơ Chanh Úc","region":"Châu Đại Dương","country":"Úc","cal":470,"goal":"Tăng Đạm","price":79000,"oldPrice":null,"rating":null,"tags":["Cá Chẽm Úc","Sốt bơ chanh"],"image":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500","desc":"Phi lê cá chẽm Barramundi biển Úc nướng bơ ghee chanh vàng măng tây."},
    {"id":49,"title":"Bowl Bơ Trừng Poached Kiểu Melbourne","region":"Châu Đại Dương","country":"Úc","cal":430,"goal":"Eat Clean","price":74000,"oldPrice":null,"rating":null,"tags":["Quả bơ","Trứng chần"],"image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500","desc":"Bát dinh dưỡng gồm bơ sáp lát, trứng Poached lòng đào, hạt chia và rau mầm."},
    {"id":50,"title":"Súp Hải Sản Kiwi Đảo New Zealand","region":"Châu Đại Dương","country":"New Zealand","cal":450,"goal":"Giảm béo","price":79000,"oldPrice":null,"rating":null,"tags":["Vẹm xanh","Súp hải sản"],"image":"https://images.unsplash.com/photo-1547592180-85f173990554?w=500","desc":"Súp vẹm xanh New Zealand hầm cùng cà chua tươi và cần tây thanh lọc."},
    {"id":501,"title":"Cơm Lứt Bò Úc Sốt Tiêu Rừng Sydney","region":"Châu Đại Dương","country":"Úc","cal":560,"goal":"Tăng cơ","price":94000,"oldPrice":null,"rating":null,"tags":["Bò Úc","Tiêu rừng"],"image":"https://images.unsplash.com/photo-1544025162-d76694265947?w=500","desc":"Bò Úc nạc xào tiêu rừng Tasmania thơm nức kèm cơm gạo lứt."},
    {"id":504,"title":"Ức Gà Nướng Sốt Bơ Hạt Macca Úc","region":"Châu Đại Dương","country":"Úc","cal":520,"goal":"Tăng cơ","price":79000,"oldPrice":null,"rating":null,"tags":["Ức gà","Hạt Macca"],"image":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500","desc":"Ức gà áp chảo phủ sốt hạt Macca bùi béo tự nhiên."},
    {"id":701,"title":"Cơm Couscous Thịt Bò Hầm Tagine Morocco","region":"Châu Phi","country":"Morocco","cal":530,"goal":"Giàu xơ","price":85000,"oldPrice":null,"rating":null,"tags":["Couscous","Bò hầm Tagine"],"image":"https://images.unsplash.com/photo-1544025162-d76694265947?w=500","desc":"Thịt bò thăn hầm nghệ, quế tươi nướng trong nồi gốm Tagine ăn kèm hạt Couscous lúa mì."},
    {"id":702,"title":"Gà Nướng Gia Vị Peri-Peri Nam Phi Cơm Lứt","region":"Châu Phi","country":"Nam Phi","cal":510,"goal":"Đổi vị","price":79000,"oldPrice":null,"rating":null,"tags":["Peri-Peri","Gà nướng"],"image":"https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=500","desc":"Ức gà nướng sốt ớt Peri-Peri chuẩn vị Nam Phi thơm cay nồng ấm."},
    {"id":703,"title":"Cơm Jollof Gạo Lứt Tôm Sú Nigeria","region":"Châu Phi","country":"Nigeria","cal":490,"goal":"Cân bằng","price":84000,"oldPrice":null,"rating":null,"tags":["Jollof Rice","Tôm sú"],"image":"https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500","desc":"Cơm gạo lứt nấu với cà chua tươi, hành tây và tôm sú nướng mộc."},
    {"id":704,"title":"Súp Đậu Phộng Gà Nướng Kiểu Ghana","region":"Châu Phi","country":"Ghana","cal":520,"goal":"Giàu đạm","price":79000,"oldPrice":null,"rating":null,"tags":["Súp đậu phộng","Gà ta"],"image":"https://images.unsplash.com/photo-1547592180-85f173990554?w=500","desc":"Súp bơ đậu phộng tự nhiên ninh cùng ức gà và cà chua thơm bùi."},
    {"id":708,"title":"Cơm Couscous Cá Hồi Sốt Chanh Thảo Mộc Morocco","region":"Châu Phi","country":"Morocco","cal":540,"goal":"Omega 3","price":90000,"oldPrice":null,"rating":null,"tags":["Cá hồi","Couscous"],"image":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500","desc":"Phi lê cá hồi áp chảo đặt trên thảm hạt Couscous trộn rau ngò tươi."},
    {"id":711,"title":"Cá Tuyết Nướng Sốt Harissa Tunisia Cơm Lứt","region":"Châu Phi","country":"Tunisia","cal":490,"goal":"Đậm vị","price":84000,"oldPrice":null,"rating":null,"tags":["Cá tuyết","Harissa"],"image":"https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500","desc":"Cá tuyết nướng phủ sốt ớt ngọt Harissa đặc sản Bắc Phi."},
    {"id":51,"title":"Bowl Hạt Quinoa & Đậu Nành Edamame","region":"Chay","country":"Quốc tế","cal":390,"goal":"Pure Vegan","price":69000,"oldPrice":null,"rating":null,"tags":["100% Chay","Quinoa"],"image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500","desc":"Bát dinh dưỡng chay với Quinoa, đậu Nhật Edamame, bơ chín và hạt ốc chó."},
    {"id":52,"title":"Cơm Lứt Nấm Mối Đen Kho Tiêu","region":"Chay","country":"Việt Nam","cal":410,"goal":"Thanh lọc","price":74000,"oldPrice":null,"rating":null,"tags":["Nấm tươi","Cơm lứt"],"image":"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500","desc":"Nấm mối đen mọng nước kho tiêu xanh ăn cùng cơm gạo lứt huyết rồng."},
    {"id":53,"title":"Lẩu Nấm Mini Đơn Chiết Keto","region":"Chay","country":"Quốc tế","cal":380,"goal":"Keto Chay","price":69000,"oldPrice":null,"rating":null,"tags":["5 Loại nấm","Tàu hũ"],"image":"https://images.unsplash.com/photo-1547592180-85f173990554?w=500","desc":"Suất lẩu cá nhân với 5 loại nấm tươi quý và đậu hũ non ăn kèm bún lứt."},
    {"id":54,"title":"Salad Đậu Chickpea Hạt Mè","region":"Chay","country":"Địa Trung Hải","cal":360,"goal":"Giảm mỡ","price":69000,"oldPrice":null,"rating":null,"tags":["Đậu gà","Mè rang"],"image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500","desc":"Đậu gà nướng giòn trộn xà lách, dưa chuột và nước sốt mè rang béo nhẹ."},
    {"id":55,"title":"Curry Đậu Lăng Vàng Kiểu Ấn Chay","region":"Chay","country":"Ấn Độ","cal":400,"goal":"Thanh lọc","price":69000,"oldPrice":null,"rating":null,"tags":["Đậu lăng","Cà ri chay"],"image":"https://images.unsplash.com/photo-1545247181-516773cae754?w=500","desc":"Đậu lăng vàng hầm cà ri nước cốt hạnh nhân ăn kèm cơm gạo lứt."},
    {"id":56,"title":"Mì Ý Sốt Nấm Mỡ & Truffle Chay","region":"Chay","country":"Ý","cal":420,"goal":"Gourmet","price":74000,"oldPrice":null,"rating":null,"tags":["Sốt Truffle","Nấm mỡ"],"image":"https://images.unsplash.com/photo-1621996346565-e3def616403c?w=500","desc":"Pasta nguyên cám sốt nấm mỡ kem yến mạch hương nấm Truffle quý giá."}
  ];

  const state = { user: null, products: FALLBACK_PRODUCTS.slice() };
  const qs = (sel, root=document) => root.querySelector(sel);
  const qsa = (sel, root=document) => [...root.querySelectorAll(sel)];
  const money = (n) => Number(n || 0).toLocaleString('vi-VN') + 'đ';
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const read = (key, fallback) => { try { const v = localStorage.getItem(key); return v ? JSON.parse(v) : fallback; } catch { return fallback; } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const getCart = () => read(KEYS.cart, []);
  const getProduct = (id) => state.products.find(p => String(p.id) === String(id));
  const cartCount = () => getCart().reduce((sum,item) => sum + Number(item.qty || 0), 0);
  const cartSubtotal = () => getCart().reduce((sum,item) => sum + Number(item.price || 0) * Number(item.qty || 0), 0);
  const shippingFor = subtotal => subtotal >= 300000 ? 0 : 25000;
  const api = async (path, options={}) => {
    const response = await fetch(`/api${path}`, { credentials:'same-origin', headers:{ 'Content-Type':'application/json', ...(options.headers || {}) }, ...options });
    if (response.status === 204) return null;
    let payload = null; try { payload = await response.json(); } catch {}
    if (!response.ok) { const err = new Error(payload?.error || 'Có lỗi xảy ra.'); err.status=response.status; err.details=payload?.details; throw err; }
    return payload;
  };

  const icon = name => {
    const paths={menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',bag:'<path d="M6 8h12l1 12H5L6 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',x:'<path d="m6 6 12 12M18 6 6 18"/>',check:'<path d="m5 12 4 4L19 6"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 20a8 8 0 0 1 16 0"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',arrowUp:'<path d="m5 12 7-7 7 7M12 5v14"/>'};
    return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`;
  };

  const showToast = message => { let t=qs('#toast'); if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t);} t.textContent=message;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),2600); };
  const setBusy = (button,busy,text='Đang xử lý…') => { if(!button)return; button.disabled=busy; if(busy){button.dataset.idleText=button.textContent;button.textContent=text;} else if(button.dataset.idleText){button.textContent=button.dataset.idleText;} };
  const goLogin = () => { const next = location.pathname + location.search; location.href = `login.html?next=${encodeURIComponent(next)}`; };
  const safeNext = (value, fallback) => { const next = String(value || ''); return next.startsWith('/') && !next.startsWith('//') ? next : fallback; };
  const requireUser = message => { if(!state.user){showToast(message || 'Vui lòng đăng nhập để tiếp tục.');setTimeout(goLogin,600);return false;}return true; };

  async function hydrateSession(){ try { const data=await api('/auth/me'); state.user=data?.user||null; } catch { state.user=null; } }
  async function hydrateProducts(){ try { const data=await api('/products'); if(Array.isArray(data?.items)&&data.items.length) state.products=data.items; } catch { /* fallback data keeps the UI available while the API is unreachable */ } }

  function renderShell(){
    const page=document.body.dataset.page||'';
    const links=NAV.map(([href,label,key])=>`<a href="${href}" class="${page===key?'active':''}"${page===key?' aria-current=\"page\"':''}>${label}</a>`).join('');
    const user=state.user;
    const auth=user ? `<a class="btn btn-soft" href="${user.role==='admin'?'admin.html':'account.html'}">${esc(user.fullname||'Tài khoản')}</a>` : `<a class="btn btn-soft" href="login.html">Đăng nhập</a>`;
    const header=`<header class="site-header"><div class="container nav"><a class="brand" href="index.html"><span class="brand-mark">F</span>FitMeal</a><nav class="nav-links">${links}</nav><div class="nav-actions"><a class="nav-icon" href="cart.html" aria-label="Giỏ hàng">${icon('bag')}<span class="cart-count" id="cartCount">${cartCount()}</span></a>${auth}<button class="mobile-toggle" type="button" aria-label="Mở menu" data-mobile-toggle>${icon('menu')}</button></div></div><div class="mobile-panel" data-mobile-panel><div class="container">${links}${user?'<a href="account.html">Tài khoản</a>':'<a href="login.html">Đăng nhập</a>'}<a href="cart.html">Giỏ hàng · ${cartCount()}</a></div></div></header>`;
    const footer=`<footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark">F</span>FitMeal</a><p style="max-width:290px;margin-top:12px">Suất ăn dinh dưỡng cá nhân hóa theo mục tiêu và khẩu vị, với trải nghiệm đặt món gọn gàng từ lựa chọn đến theo dõi đơn.</p></div><div><h4>Khám phá</h4><ul><li><a href="menu.html">Thực đơn</a></li><li><a href="Lotrinhhoa.html">Cá nhân hóa</a></li><li><a href="orders.html">Đơn hàng</a></li><li><a href="sitemap.html">Sơ đồ website</a></li></ul></div><div><h4>Hỗ trợ</h4><ul><li><a href="contact.html">Liên hệ</a></li><li>08:00 – 22:00 mỗi ngày</li><li>1900 6868</li></ul></div><div><h4>Thanh toán</h4><ul><li>VNPAY</li><li>COD khi nhận món</li><li>HTTPS + session bảo mật</li></ul></div></div><div class="footer-bottom"><span>© 2026 FitMeal</span><span>Full-stack · PostgreSQL · VNPAY</span></div></div></footer>`;
    document.body.insertAdjacentHTML('afterbegin',header);document.body.insertAdjacentHTML('beforeend',footer);
    qsa('[data-mobile-toggle]').forEach(btn=>btn.addEventListener('click',()=>qs('[data-mobile-panel]')?.classList.toggle('open')));updateCartCount();
  }
  function updateCartCount(){const c=cartCount();qsa('#cartCount').forEach(el=>el.textContent=c);qsa('.mobile-panel a:last-child').forEach(el=>el.textContent=`Giỏ hàng · ${c}`);}

  function addToCart(productId,qty=1,options={}){const p=getProduct(productId);if(!p)return;const cart=getCart();const rice=options.rice||'Gạo lứt';const note=options.note||'';const key=`${p.id}|${rice}|${note}`;const existing=cart.find(i=>i.key===key);if(existing)existing.qty+=Math.max(1,Number(qty)||1);else cart.push({key,id:p.id,title:p.title,price:p.price,image:p.image,qty:Math.max(1,Number(qty)||1),rice,note});write(KEYS.cart,cart);updateCartCount();showToast(`Đã thêm ${p.title} vào giỏ hàng.`);}
  function setSingleCart(productId,qty=1,options={}){write(KEYS.cart,[]);addToCart(productId,qty,options);location.href='order.html';}

  function renderProductCard(p){return `<article class="card product-card"><div class="product-media"><img src="${esc(p.image)}" loading="lazy" decoding="async" width="1000" height="1000" alt="${esc(p.title)}"><span class="product-tag">${esc(p.region)}</span></div><div class="product-body"><h3 class="product-title">${esc(p.title)}</h3><p class="product-desc">${esc(p.desc)}</p><div class="tagline"><span class="mini-tag">${esc(p.cal)} kcal</span><span class="mini-tag">${esc(p.goal)}</span>${(p.tags||[]).slice(0,2).map(t=>`<span class="mini-tag">${esc(t)}</span>`).join('')}</div><div class="product-meta"><span class="muted">${esc(p.country)}</span><span class="review-mini">${p.reviewCount?`★ ${Number(p.rating||0).toFixed(1)} · ${p.reviewCount} đánh giá`:'Chưa có đánh giá'}</span></div><div class="product-actions"><button class="btn btn-primary" type="button" data-buy="${p.id}">Đặt món</button><button class="icon-action" type="button" data-view="${p.id}" aria-label="Xem chi tiết món">${icon('arrow')}</button></div></div></article>`;}
  function bindProductActions(root=document){qsa('[data-buy]',root).forEach(b=>b.addEventListener('click',()=>setSingleCart(b.dataset.buy,1)));qsa('[data-view]',root).forEach(b=>b.addEventListener('click',()=>openProductModal(getProduct(b.dataset.view))));}

  async function loadProductReviews(p, modal){const box=qs('#reviewContent',modal);if(!box)return;box.innerHTML='<div class="review-loading">Đang tải đánh giá…</div>';try{const data=await api(`/products/${encodeURIComponent(p.id)}/reviews`);const reviews=Array.isArray(data?.items)?data.items:[];const avg=reviews.length?(reviews.reduce((sum,r)=>sum+Number(r.rating||0),0)/reviews.length):Number(p.rating||0);const summary=`<div class="review-summary"><span class="stars">${reviews.length?'★★★★★':'☆☆☆☆☆'}</span><strong>${reviews.length?avg.toFixed(1):'Chưa có'}</strong><span class="muted">${reviews.length?`${reviews.length} đánh giá`: 'Hãy là người đầu tiên đánh giá món này'}</span></div>`;const cards=reviews.length?`<div class="reviews-list">${reviews.map(r=>`<article class="review-card"><div class="review-card-head"><div><strong>${esc(r.title||'Đánh giá món ăn')}</strong><div class="review-stars">${'★'.repeat(Number(r.rating||0))}${'☆'.repeat(5-Number(r.rating||0))}</div></div><small>${esc(r.full_name||'Khách hàng')} ${r.is_verified?'· Đã mua hàng':''}</small></div><p>${esc(r.body)}</p></article>`).join('')}</div>`:'<div class="review-empty">Món này chưa có đánh giá công khai. Hãy thử món và chia sẻ cảm nhận của bạn.</div>';const form=state.user?`<form class="review-form" id="reviewForm"><div class="row"><select class="select" name="rating" required><option value="5">★★★★★ · Rất ngon</option><option value="4">★★★★☆ · Rất tốt</option><option value="3">★★★☆☆ · Ổn</option><option value="2">★★☆☆☆ · Chưa hợp</option><option value="1">★☆☆☆☆ · Không phù hợp</option></select><input class="input" name="title" maxlength="120" placeholder="Tiêu đề đánh giá (tùy chọn)"></div><textarea class="input" name="body" minlength="8" maxlength="1200" placeholder="Bạn thích món này ở điểm nào?" required></textarea><button class="btn btn-soft" type="submit">Gửi đánh giá</button></form>`:'<div class="review-login-note">Đăng nhập và hoàn tất đơn có món này để gửi đánh giá đã xác thực.</div>';box.innerHTML=summary+cards+form;const rf=qs('#reviewForm',box);rf?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(rf).entries());try{await api(`/products/${encodeURIComponent(p.id)}/reviews`,{method:'POST',body:JSON.stringify({rating:Number(data.rating),title:data.title,body:data.body})});showToast('Đã gửi đánh giá của bạn.');await loadProductReviews(p,modal);}catch(err){showToast(err.message);}})}catch{box.innerHTML='<div class="review-empty">Chưa thể tải đánh giá lúc này. Bạn vẫn có thể xem thông tin món và đặt hàng bình thường.</div>';}}
  function detailPreparation(p){const text=String(p.desc||'').trim();const tags=(p.tags||[]).slice(0,4);const region=String(p.region||'');const prep=region==='Việt Nam'?'Ưu tiên xử lý nguyên liệu tươi, nêm vừa vị và kiểm soát lượng dầu trong quá trình nấu.':region==='Châu Á'?'Sơ chế nguyên liệu, nấu nhanh để giữ độ tươi và cân bằng vị đặc trưng của món.':region==='Châu Âu'?'Áp chảo/nướng hoặc sốt ở nhiệt độ vừa để giữ độ mềm của nguyên liệu chính và hương thơm thảo mộc.':region==='Châu Mỹ'?'Nướng hoặc áp chảo nguyên liệu chính, kết hợp rau và sốt theo phong cách nhẹ vị.':region==='Châu Đại Dương'?'Ưu tiên phương pháp nướng, áp chảo hoặc hấp để giữ vị tự nhiên của nguyên liệu chính.':region==='Châu Phi'?'Ninh/nấu chậm hoặc nướng với hỗn hợp gia vị đặc trưng, cân đối rau và tinh bột.':'Chuẩn bị theo phong cách nhà bếp FitMeal, ưu tiên vị tự nhiên và khẩu phần cân đối.';return {prep,ingredients:tags.length?tags:['Nguyên liệu chính theo mô tả món'],note:text};}
  async function openProductModal(p){if(!p)return;let modal=qs('#productModal');if(!modal){modal=document.createElement('div');modal.id='productModal';modal.className='modal';modal.innerHTML=`<div class="modal-card"><button class="modal-close" type="button" data-modal-close>${icon('x')}</button><div class="modal-body" id="productModalBody"></div></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal();});qs('[data-modal-close]',modal).addEventListener('click',closeModal);}const d=detailPreparation(p);qs('#productModalBody',modal).innerHTML=`<div class="modal-product"><img src="${esc(p.image)}" loading="lazy" decoding="async" width="1000" height="1000" alt="${esc(p.title)}"><div><span class="eyebrow">${esc(p.region)} · ${esc(p.country)}</span><h2 style="font:700 38px/1.05 'Playfair Display',serif;margin:14px 0 8px">${esc(p.title)}</h2><div class="rating-row"><span class="stars">★★★★★</span><b>${p.reviewCount?Number(p.rating||0).toFixed(1):'—'}</b><span>${p.reviewCount?`${p.reviewCount} đánh giá`:'Chưa có đánh giá'}</span></div><div class="price-lg">${money(p.price)}</div><p class="muted">${esc(p.desc)}</p><div class="info-grid"><div class="info-item"><small>Năng lượng</small><strong>${esc(p.cal)} kcal</strong></div><div class="info-item"><small>Mục tiêu</small><strong>${esc(p.goal)}</strong></div><div class="info-item"><small>Khẩu phần</small><strong>1 suất</strong></div><div class="info-item"><small>Giá hiện tại</small><strong>${money(p.price)}</strong></div></div><div class="detail-sections"><section class="detail-section"><h3>Nguyên liệu nổi bật</h3><ul class="detail-list">${d.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="detail-section"><h3>Cách chế biến</h3><p class="detail-copy">${esc(d.prep)}</p><p class="muted detail-source">${esc(d.note)}</p></section><section class="detail-section"><h3>Đánh giá người dùng</h3><div id="reviewContent"></div></section></div><button class="btn btn-primary btn-lg btn-block" type="button" data-modal-buy="${p.id}">Thêm vào giỏ hàng · ${money(p.price)}</button></div></div>`;qs('[data-modal-buy]',modal).addEventListener('click',()=>{addToCart(p.id,1);closeModal();});modal.classList.add('open');document.body.classList.add('modal-open');await loadProductReviews(p,modal);}
  function closeModal(){qs('.modal.open')?.classList.remove('open');document.body.classList.remove('modal-open');}

  function initHome(){const p=getProduct(1);initFoodRail();if(!p)return;const img=qs('[data-product-image]');if(img)img.src=p.image;qsa('[data-product-title]').forEach(el=>el.textContent=p.title);const price=qs('[data-product-price]');if(price)price.textContent=money(p.price);const old=qs('[data-product-old]');if(old)old.textContent=p.oldPrice?money(p.oldPrice):'';const desc=qs('[data-product-desc]');if(desc)desc.textContent=p.desc;const tags=qs('[data-product-tags]');if(tags)tags.innerHTML=(p.tags||[]).map(t=>`<span class="mini-tag">${esc(t)}</span>`).join('');const grid=qs('#homeProducts');if(grid){grid.innerHTML=state.products.slice(0,3).map(renderProductCard).join('');bindProductActions(grid);}const q=qs('#productQty');qsa('[data-qty-step]').forEach(btn=>btn.addEventListener('click',()=>{q.value=Math.max(1,(Number(q.value)||1)+Number(btn.dataset.qtyStep));}));qs('#homeAdd')?.addEventListener('click',()=>addToCart(1,Number(q?.value)||1,{rice:qs('#homeRice')?.value,note:qs('#homeNote')?.value.trim()}));qs('#homeBuy')?.addEventListener('click',()=>setSingleCart(1,Number(q?.value)||1,{rice:qs('#homeRice')?.value,note:qs('#homeNote')?.value.trim()}));}

  function initFoodRail(){const rail=qs('#foodRail');if(!rail)return;const make=items=>items.map(p=>`<button class="food-rail-card" type="button" data-view="${p.id}"><img src="${esc(p.image)}" loading="lazy" decoding="async" alt="${esc(p.title)}"><span class="food-rail-card-body"><strong>${esc(p.title)}</strong><small>${esc(p.cal)} kcal · ${esc(p.goal)}</small></span></button>`).join('');const doubled=[...state.products,...state.products];rail.innerHTML=`<div class="food-rail-track">${make(doubled)}</div>`;bindProductActions(rail);rail.addEventListener('click',e=>{const card=e.target.closest('.food-rail-card');if(!card)return;rail.classList.toggle('is-paused');});}

  function initMenu(){const grid=qs('#productGrid');if(!grid)return;const region=qs('#regionFilter'),goal=qs('#goalFilter'),search=qs('#menuSearch');const params=new URLSearchParams(location.search);const rawRecommendedGoal=params.get('goal')||'';const recommendedGoal=({weight_loss:'Giảm cân',maintain:'Giữ dáng',muscle_gain:'Tăng cơ',weight_gain:'Tăng cơ'}[rawRecommendedGoal]||rawRecommendedGoal);let activeGoal=goal?.value||'all';const recommended=params.get('recommended')==='1';const render=()=>{const term=(search?.value||'').trim().toLowerCase();let filtered=state.products.filter(p=>(region?.value==='all'||!region?.value||p.region===region.value)&&(activeGoal==='all'||p.goal===activeGoal)&&(!term||`${p.title} ${p.country} ${p.region} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(term)));if(recommended&&recommendedGoal&&activeGoal==='all'&&!term&&(!region?.value||region.value==='all')){filtered=[...filtered].sort((a,b)=>Number(b.goal===recommendedGoal)-Number(a.goal===recommendedGoal));}grid.innerHTML=filtered.length?filtered.map(renderProductCard).join(''):`<div class="card empty" style="grid-column:1/-1"><strong>Chưa tìm thấy món phù hợp</strong>Thử đổi từ khóa hoặc bộ lọc.</div>`;bindProductActions(grid);if(qs('#resultCount'))qs('#resultCount').textContent=`${filtered.length} món`;if(qs('#menuTotal'))qs('#menuTotal').textContent=`${state.products.length} món trong kho thực đơn`;if(qs('#recommendedNote'))qs('#recommendedNote').hidden=!recommended;};region?.addEventListener('change',render);goal?.addEventListener('change',()=>{activeGoal=goal.value; qsa('[data-goal-chip]').forEach(c=>c.classList.toggle('active',c.dataset.goalChip===activeGoal));render();});search?.addEventListener('input',render);qsa('[data-goal-chip]').forEach(c=>c.addEventListener('click',()=>{activeGoal=c.dataset.goalChip;if(goal)goal.value=activeGoal;qsa('[data-goal-chip]').forEach(x=>x.classList.toggle('active',x===c));render();}));if(qs('#recommendedNote'))qs('#recommendedNote').hidden=!recommended;render();}

  function initPlan(){const form=qs('#planForm');if(!form)return;const saved=read(KEYS.plan,null),result=qs('#planResult');['age','height','weight','activity','gender','goal'].forEach(k=>{if(saved&&form.elements[k])form.elements[k].value=saved[k]??form.elements[k].value;});const calculate=()=>{const age=Number(form.elements.age.value),height=Number(form.elements.height.value),weight=Number(form.elements.weight.value),activity=Number(form.elements.activity.value),gender=form.elements.gender.value,goal=form.elements.goal.value;if(!age||!height||!weight){result.innerHTML='<div class="card empty"><strong>Điền vài thông tin cơ bản</strong>Hệ thống sẽ tính chỉ số ước tính và gợi ý lộ trình.</div>';return;}const bmr=gender==='male'?10*weight+6.25*height-5*age+5:10*weight+6.25*height-5*age-161;const tdee=Math.round(bmr*activity);const target=goal==='gain'?Math.round(tdee+250):goal==='loss'?Math.round(tdee-350):Math.round(tdee);const meals=Math.max(3,Math.min(5,Math.round(target/520)));const planName=goal==='loss'?'Lean Reset 21 ngày':goal==='gain'?'Lean Build 30 ngày':'Balanced 14 ngày';result.innerHTML=`<div class="panel"><span class="kicker">Kết quả ước tính</span><h2 style="font:700 34px/1.1 'Playfair Display',serif;margin-top:4px">${planName}</h2><p class="muted">Mức năng lượng mục tiêu tham khảo: ${target.toLocaleString('vi-VN')} kcal/ngày</p><div class="grid-3" style="grid-template-columns:repeat(2,1fr);margin:16px 0"><div class="metric-card"><small>BMR</small><strong>${Math.round(bmr)}</strong><span class="muted">kcal/ngày</span></div><div class="metric-card"><small>TDEE</small><strong>${tdee}</strong><span class="muted">kcal/ngày</span></div></div><div class="metric-card"><small>Gợi ý số suất</small><strong>${meals}</strong><span class="muted">bữa/ngày</span></div><button class="btn btn-primary btn-lg btn-block" type="button" id="savePlan" style="margin-top:14px">Lưu lộ trình</button></div>`;qs('#savePlan')?.addEventListener('click',()=>{write(KEYS.plan,{...Object.fromEntries(new FormData(form).entries()),bmr,tdee,target,planName,updatedAt:new Date().toISOString()});showToast('Đã lưu lộ trình trên thiết bị này.');});};form.addEventListener('submit',e=>{e.preventDefault();calculate();});calculate();}

  function renderCart(){const list=qs('#cartList');if(!list)return;const cart=getCart(),subtotal=cartSubtotal(),shipping=shippingFor(subtotal),total=subtotal+shipping;qs('#cartSubtotal').textContent=money(subtotal);qs('#cartShipping').textContent=shipping?money(shipping):'Miễn phí';qs('#cartGrand').textContent=money(total);const checkout=qs('#checkoutCart');if(!cart.length){list.innerHTML='<div class="empty"><strong>Giỏ hàng đang trống</strong>Chọn một món yêu thích từ thực đơn để bắt đầu.<div style="margin-top:14px"><a class="btn btn-primary" href="menu.html">Khám phá thực đơn</a></div></div>';if(checkout)checkout.disabled=true;return;}if(checkout)checkout.disabled=false;list.innerHTML=cart.map(i=>`<div class="cart-item"><img src="${esc(i.image)}" loading="lazy" decoding="async" width="1000" height="1000" alt="${esc(i.title)}"><div class="cart-info"><strong>${esc(i.title)}</strong><small>${esc(i.rice||'Gạo lứt')}${i.note?` · ${esc(i.note)}`:''}</small><div class="cart-actions"><div class="mini-qty"><button type="button" data-minus="${esc(i.key)}">−</button><input value="${esc(i.qty)}" readonly><button type="button" data-plus="${esc(i.key)}">+</button></div><button type="button" class="btn btn-danger" style="padding:7px 10px" data-remove="${esc(i.key)}">Xóa</button></div></div><div class="cart-price">${money(i.price*i.qty)}</div></div>`).join('');qsa('[data-plus]',list).forEach(b=>b.addEventListener('click',()=>updateCartItem(b.dataset.plus,1)));qsa('[data-minus]',list).forEach(b=>b.addEventListener('click',()=>updateCartItem(b.dataset.minus,-1)));qsa('[data-remove]',list).forEach(b=>b.addEventListener('click',()=>removeCartItem(b.dataset.remove)));}
  function updateCartItem(key,delta){const cart=getCart(),item=cart.find(x=>x.key===key);if(!item)return;item.qty=Math.max(1,Number(item.qty)+delta);write(KEYS.cart,cart);updateCartCount();renderCart();}
  function removeCartItem(key){write(KEYS.cart,getCart().filter(x=>x.key!==key));updateCartCount();renderCart();showToast('Đã xóa món khỏi giỏ hàng.');}
  function initCart(){renderCart();qs('#checkoutCart')?.addEventListener('click',()=>{if(getCart().length){if(requireUser('Đăng nhập trước khi đặt hàng.'))location.href='order.html';}});qs('#clearCart')?.addEventListener('click',()=>{write(KEYS.cart,[]);updateCartCount();renderCart();});}

  function initOrder(){const form=qs('#orderForm');if(!form)return;if(!requireUser('Đăng nhập để tạo đơn hàng.')){form.hidden=true;return;}const cart=getCart();if(!cart.length){qs('#orderGuard').innerHTML='<div class="card empty"><strong>Chưa có sản phẩm để đặt</strong>Quay lại thực đơn hoặc giỏ hàng để tiếp tục.<div style="margin-top:14px"><a class="btn btn-primary" href="menu.html">Mở thực đơn</a></div></div>';form.hidden=true;return;}const user=state.user;form.elements.fullname.value=user.fullname||'';form.elements.email.value=user.email||'';form.elements.phone.value=user.phone||'';form.elements.address.value=user.address||'';const subtotal=cartSubtotal(),shipping=shippingFor(subtotal),total=subtotal+shipping;qs('#orderItems').innerHTML=cart.map(i=>`<div class="summary-line"><span>${esc(i.title)} × ${i.qty}</span><strong>${money(i.price*i.qty)}</strong></div>`).join('')+`<div class="summary-line"><span>Giao hàng</span><strong>${shipping?money(shipping):'Miễn phí'}</strong></div>`;qs('#orderTotal').textContent=money(total);form.addEventListener('submit',e=>{e.preventDefault();sessionStorage.setItem(KEYS.checkout,JSON.stringify({customer:{fullName:form.elements.fullname.value.trim(),email:form.elements.email.value.trim().toLowerCase(),phone:form.elements.phone.value.trim(),address:form.elements.address.value.trim(),note:form.elements.note.value.trim()},items:getCart()}));location.href='thanhtoan.html';});}

  const checkoutDraft=()=>{try{return JSON.parse(sessionStorage.getItem(KEYS.checkout)||'null');}catch{return null;}};
  const clearCheckout=()=>{sessionStorage.removeItem(KEYS.checkout);write(KEYS.cart,[]);updateCartCount();};
  const statusLabel = status => ({pending_payment:'Chờ thanh toán',processing:'Đang xử lý',confirmed:'Đã xác nhận',shipping:'Đang giao',completed:'Hoàn tất',cancelled:'Đã hủy'})[status]||status;
  const statusClass = status => status==='cancelled'?'status-red':status==='completed'?'status-gold':'status-green';
  const paymentLabel = value => value==='vnpay'?'VNPAY':'COD';
  function initPayment(){
    const draft=checkoutDraft();
    if(!draft||!getCart().length){qs('#paymentGuard').innerHTML='<div class="card empty"><strong>Phiên đặt hàng chưa sẵn sàng</strong>Vui lòng quay lại giỏ hàng và nhập thông tin giao hàng.<div style="margin-top:14px"><a class="btn btn-primary" href="cart.html">Quay lại giỏ hàng</a></div></div>';qs('#paymentForm')?.setAttribute('hidden','hidden');return;}
    if(!requireUser('Đăng nhập để thanh toán.'))return;
    qs('#paymentItems').innerHTML=getCart().map(i=>`<div class="summary-line"><span>${esc(i.title)} × ${i.qty}</span><strong>${money(i.price*i.qty)}</strong></div>`).join('');
    const subtotal=cartSubtotal(),shipping=shippingFor(subtotal),total=subtotal+shipping;
    qs('#paymentShipping').textContent=shipping?money(shipping):'Miễn phí';
    qs('#paymentTotal').textContent=money(total);
    const button=qs('#paymentForm button[type="submit"]');
    qs('#paymentForm').addEventListener('submit',async e=>{
      e.preventDefault();
      const payment=qs('input[name="payment"]:checked')?.value||'vnpay';
      setBusy(button,true,'Đang xử lý…');
      try{
        let orderId=draft.orderId;
        let order;
        if(orderId){
          const existing=await api(`/orders/${encodeURIComponent(orderId)}`);order=existing.order;
          if(order.payment_status==='paid'){clearCheckout();location.href=`xacnhandon.html?id=${encodeURIComponent(order.id)}&payment=success`;return;}
        }else{
          const created=await api('/orders',{method:'POST',body:JSON.stringify({customer:draft.customer,paymentMethod:payment,items:getCart().map(i=>({productId:i.id,quantity:Number(i.qty),rice:i.rice,note:i.note}))})});
          order=created.order;orderId=order.id;draft.orderId=orderId;draft.paymentMethod=payment;sessionStorage.setItem(KEYS.checkout,JSON.stringify(draft));
        }
        if(payment==='cod'){clearCheckout();location.href=`xacnhandon.html?id=${encodeURIComponent(orderId)}&payment=cod`;return;}
        const paymentData=await api('/payments/vnpay/create',{method:'POST',body:JSON.stringify({orderId})});
        clearCheckout();location.href=paymentData.paymentUrl;
      }catch(error){showToast(error.message);setBusy(button,false);}
    });
  }

  function initQr(){const draft=checkoutDraft();if(!draft){location.href='thanhtoan.html';return;}location.replace('thanhtoan.html');}

  async function initConfirmation(){const id=new URLSearchParams(location.search).get('id'),payment=new URLSearchParams(location.search).get('payment');if(!id){qs('#confirmBody').innerHTML='<div class="empty"><strong>Thiếu mã đơn hàng</strong>Không có đơn hàng nào để hiển thị.</div>';return;}try{const data=await api(`/orders/${encodeURIComponent(id)}`);const order=data.order;qs('#orderId').textContent='#'+order.order_code;qs('#orderTotalConfirm').textContent=money(order.total);qs('#customerName').textContent=order.customer_name;qs('#customerPhone').textContent=order.customer_phone;qs('#customerAddress').textContent=order.shipping_address;qs('#orderItemsConfirm').innerHTML=order.items.map(i=>`<div class="summary-line"><span>${esc(i.title_snapshot)} × ${i.quantity}</span><strong>${money(i.unit_price*i.quantity)}</strong></div>`).join('')+`<div class="summary-line"><span>Phí giao hàng</span><strong>${order.shipping_fee?money(order.shipping_fee):'Miễn phí'}</strong></div>`;const notice=qs('#confirmBody .notice');if(notice){notice.innerHTML=payment==='success'?'<strong>Thanh toán VNPAY thành công.</strong> Đơn hàng đang được xử lý.':payment==='failed'?'<strong>Thanh toán chưa thành công.</strong> Đơn hàng đã được cập nhật trạng thái; bạn có thể tạo lại đơn mới.':`Trạng thái hiện tại: <strong>${esc(statusLabel(order.status))}</strong>. Thanh toán: <strong>${esc(paymentLabel(order.payment_method))}</strong>.`;}}catch(error){qs('#confirmBody').innerHTML=`<div class="empty"><strong>${esc(error.message)}</strong>Hãy đăng nhập bằng tài khoản đã tạo đơn rồi thử lại.</div>`;}}

  async function initLogin(){const form=qs('#loginForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"]');setBusy(button,true);try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({email:form.elements.email.value.trim().toLowerCase(),password:form.elements.password.value})});state.user=data.user;const next=safeNext(new URLSearchParams(location.search).get('next'), state.user.role==='admin'?'admin.html':'account.html');location.href=next;}catch(error){showToast(error.message);setBusy(button,false);}});}
  async function initRegister(){const form=qs('#registerForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());if(data.password!==data.confirmPassword){showToast('Mật khẩu xác nhận chưa khớp.');return;}if(data.password.length<8){showToast('Mật khẩu cần ít nhất 8 ký tự.');return;}const button=form.querySelector('button[type="submit"]');setBusy(button,true);try{const result=await api('/auth/register',{method:'POST',body:JSON.stringify({email:data.email,fullName:data.fullname,phone:data.phone,address:data.address,password:data.password})});state.user=result.user;location.href=safeNext(new URLSearchParams(location.search).get('next'),'account.html');}catch(error){showToast(error.message);setBusy(button,false);}});}

  async function signOut(){try{await api('/auth/logout',{method:'POST'});}catch{}state.user=null;location.href='index.html';}
  async function initAccount(){if(!requireUser())return;if(state.user.role==='admin'){location.href='admin.html';return;}const u=state.user;qs('#accName').textContent=u.fullname;qs('#accEmail').textContent=u.email;qs('#accPhone').textContent=u.phone||'Chưa cập nhật';qs('#accAddress').textContent=u.address||'Chưa cập nhật';qs('#accAvatar').textContent=(u.fullname||'F').split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase();try{const data=await api('/orders');const orders=data.items||[];qs('#accOrders').textContent=orders.length;qs('#accSpending').textContent=money(orders.reduce((s,o)=>s+Number(o.total||0),0));qs('#accActive').textContent=orders.filter(o=>!['completed','cancelled'].includes(o.status)).length;qs('#recentOrders').innerHTML=orders.slice(0,3).map(o=>`<div class="card" style="padding:16px"><div style="display:flex;justify-content:space-between;gap:10px"><strong>#${esc(o.order_code)}</strong><span class="status ${statusClass(o.status)}">${esc(statusLabel(o.status))}</span></div><div class="muted" style="font-size:12px;margin-top:4px">${new Date(o.created_at).toLocaleString('vi-VN')} · ${esc(paymentLabel(o.payment_method))}</div><div style="margin-top:8px;font-weight:800">${money(o.total)}</div></div>`).join('')||'<div class="empty">Chưa có đơn hàng gần đây.</div>';}catch(error){showToast(error.message);}qs('#logout')?.addEventListener('click',e=>{e.preventDefault();signOut();});const f=qs('#profileForm');if(f){f.fullname.value=u.fullname||'';f.phone.value=u.phone||'';f.address.value=u.address||'';f.addEventListener('submit',async e=>{e.preventDefault();try{const result=await api('/me',{method:'PATCH',body:JSON.stringify({fullName:f.fullname.value.trim(),phone:f.phone.value.trim(),address:f.address.value.trim()})});state.user=result.user;showToast('Đã cập nhật hồ sơ.');}catch(error){showToast(error.message);}});}}

  async function initOrders(){const list=qs('#ordersList');if(!list)return;if(!requireUser())return;let status='all';const render=async()=>{list.innerHTML='<div class="card empty">Đang tải đơn hàng…</div>';try{const data=await api('/orders');let rows=data.items||[];if(status!=='all')rows=rows.filter(o=>o.status===status);list.innerHTML=rows.length?rows.map(o=>`<div class="card" style="padding:18px;margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:16px;align-items:start"><div><strong>#${esc(o.order_code)}</strong><div class="muted" style="font-size:12px">${new Date(o.created_at).toLocaleString('vi-VN')}</div></div><span class="status ${statusClass(o.status)}">${esc(statusLabel(o.status))}</span></div><div style="margin-top:12px"><strong>${esc(o.items.map(i=>i.title_snapshot).join(', '))}</strong><div class="muted" style="font-size:12px;margin-top:3px">${o.items.reduce((s,i)=>s+i.quantity,0)} phần · ${esc(paymentLabel(o.payment_method))} · ${esc(o.payment_status)}</div></div><div style="display:flex;justify-content:space-between;gap:16px;align-items:end;margin-top:14px;padding-top:12px;border-top:1px solid var(--line)"><span class="muted" style="font-size:12px">${esc(o.shipping_address)}</span><strong>${money(o.total)}</strong></div><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:12px"><a class="btn btn-soft" href="xacnhandon.html?id=${encodeURIComponent(o.id)}">Chi tiết</a>${!['completed','cancelled'].includes(o.status)?`<button class="btn btn-danger" data-cancel-order="${esc(o.id)}">Hủy đơn</button>`:''}</div></div>`).join(''):'<div class="card empty"><strong>Không có đơn ở trạng thái này</strong>Thử bộ lọc khác.</div>';qsa('[data-cancel-order]',list).forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Bạn có chắc muốn hủy đơn này?'))return;try{await api(`/orders/${b.dataset.cancelOrder}/cancel`,{method:'POST'});showToast('Đã hủy đơn hàng.');render();}catch(error){showToast(error.message);}}));}catch(error){list.innerHTML=`<div class="card empty"><strong>${esc(error.message)}</strong></div>`;}};qsa('[data-order-status]').forEach(b=>b.addEventListener('click',()=>{qsa('[data-order-status]').forEach(x=>x.classList.remove('active'));b.classList.add('active');status=b.dataset.orderStatus;render();}));render();}

  async function initContact(){const form=qs('#contactForm');if(!form)return;const name=state.user?.fullname,email=state.user?.email; if(name&&form.elements.fullname)form.elements.fullname.value=name;if(email&&form.elements.email)form.elements.email.value=email;form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"]');setBusy(button,true);const data=Object.fromEntries(new FormData(form).entries());try{await api('/contact',{method:'POST',body:JSON.stringify({fullName:data.fullname,email:data.email,phone:data.phone,subject:data.subject,message:data.message})});form.reset();showToast('Đã ghi nhận yêu cầu. FitMeal sẽ liên hệ với bạn.');}catch(error){showToast(error.message);}finally{setBusy(button,false);}});}

  async function initAdmin(){if(!state.user||state.user.role!=='admin'){location.href='login.html';return;}const filter=qs('#adminFilter');const render=async()=>{try{const data=await api(`/admin/stats?filter=${encodeURIComponent(filter?.value||'all')}`);const s=data.stats||{};qs('#statCustomers').textContent=s.customers||0;qs('#statOrders').textContent=s.orders||0;qs('#statRevenue').textContent=money(s.revenue);qs('#statToday').textContent=money(s.today);const table=qs('#adminOrders');table.innerHTML=(data.orders||[]).map(o=>`<tr><td>#${esc(o.order_code)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.customer_phone)}</td><td>${new Date(o.created_at).toLocaleString('vi-VN')}</td><td>${esc(paymentLabel(o.payment_method))} · ${esc(o.payment_status)}</td><td><strong>${money(o.total)}</strong></td><td><select class="select" style="min-width:145px;padding:8px 30px 8px 10px" data-admin-status="${esc(o.id)}">${['processing','confirmed','shipping','completed','cancelled'].map(st=>`<option value="${st}" ${o.status===st?'selected':''}>${esc(statusLabel(st))}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Chưa có dữ liệu.</td></tr>';qsa('[data-admin-status]',table).forEach(select=>select.addEventListener('change',async()=>{try{await api(`/admin/orders/${select.dataset.adminStatus}/status`,{method:'PATCH',body:JSON.stringify({status:select.value})});showToast('Đã cập nhật trạng thái.');}catch(error){showToast(error.message);render();}}));const customerTable=qs('#customerTable');customerTable.innerHTML=(data.customers||[]).map(c=>`<tr><td>${esc(c.full_name)}</td><td>${esc(c.phone||'—')}</td><td>${esc(c.email)}</td><td>${c.order_count}</td><td><strong>${money(c.total_spent)}</strong></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Chưa có khách hàng.</td></tr>';}catch(error){showToast(error.message);}};filter?.addEventListener('change',render);qs('#clearDemo')?.remove();qs('#adminLogout')?.addEventListener('click',e=>{e.preventDefault();signOut();});render();}

  const inits={home:initHome,menu:initMenu,survey:()=>{},plan:initPlan,cart:initCart,order:initOrder,payment:initPayment,qr:initQr,confirmation:initConfirmation,login:initLogin,register:initRegister,account:initAccount,orders:initOrders,contact:initContact,admin:initAdmin,about:()=>{},stories:()=>{}};
  async function init(){await hydrateSession();await hydrateProducts();renderShell();await (inits[document.body.dataset.page]||(()=>{}))();}
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});window.addEventListener('storage',updateCartCount);document.addEventListener('DOMContentLoaded',()=>init());
  window.FitMeal={addToCart,money,showToast};
})();
